package com.luxoft.data.examples.repositories;

import com.luxoft.data.examples.model.Address;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.data.rest.core.annotation.RestResource;

import java.util.List;

@RepositoryRestResource
//@Api(tags = "Spring-data-REST autogenerated")
public interface AddressRepository extends JpaRepository<Address, Long> {


}
